################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# footer content
footer_content = "A family-owned retailer best known for our Legendary Collection - guitars amps and effects owned and used by Eric Clapton, Jerry Garcia, Carlos Santana, Eric Johnson and others. We also offer a wide variety of high-end, accessibly-priced guitars and accessories."