############### English navigation ################

[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

# [[main]]
# name = "Shop"
# url = "shop/"
# weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Terms Conditions"
url = "terms-conditions/"
weight = 4
